'use client'
import styles from './ThemeTab.module.css'
import { showToast } from '@/components/Toast'

interface PaletteColor { hex: string; name: string; usage: string }
interface MoodTile { emoji: string; title: string; description: string; category: string }
interface MoodboardData {
    title: string; vibe: string; palette: PaletteColor[]; tiles: MoodTile[]
    tablescape: string; lighting: string; welcomeSign: string; partyFavor: string; hashtag: string
}
interface MoodboardState { board: MoodboardData | null; pinnedTileIndices: number[] }
interface CakeConcept {
    id: string; name: string; style: string; tiers: number; servings: string; flavors: string[]
    decorationStyle: string; dietaryNotes: string; estimatedPrice: string; emoji: string
}
interface CakeSelectorState { concepts: CakeConcept[]; selectedConceptId: string | null }
interface PlanData { eventType: string; date: string; guests: string; location: string; theme: string; budget: string }

interface VendorBriefProps {
    moodboard: MoodboardState | null
    cake: CakeSelectorState | null
    planData: PlanData
    guestDietarySummary: string
    onClose: () => void
}

export default function VendorBrief({ moodboard, cake, planData, guestDietarySummary, onClose }: VendorBriefProps) {
    const board = moodboard?.board
    const selectedCake = cake?.concepts.find(c => c.id === cake.selectedConceptId)
    const pinnedTiles = moodboard?.pinnedTileIndices.map(i => board?.tiles[i]).filter(Boolean) || []

    const buildBriefText = (): string => {
        const lines: string[] = []
        lines.push('=== PARTY DECOR BRIEF ===')
        lines.push('')
        lines.push(`Event: ${planData.eventType}`)
        lines.push(`Date: ${planData.date}`)
        lines.push(`Guests: ${planData.guests}`)
        lines.push(`Location: ${planData.location}`)
        lines.push(`Budget: ${planData.budget}`)
        lines.push(`Theme: ${planData.theme}`)
        lines.push('')

        if (board) {
            lines.push('--- COLOR PALETTE ---')
            board.palette.forEach(c => {
                lines.push(`  ${c.name} (${c.hex}) — ${c.usage}`)
            })
            lines.push('')

            lines.push(`--- VIBE ---`)
            lines.push(board.vibe)
            lines.push('')

            if (pinnedTiles.length > 0) {
                lines.push('--- SELECTED INSPIRATIONS ---')
                pinnedTiles.forEach(t => {
                    if (t) lines.push(`  ${t.emoji} ${t.title}: ${t.description}`)
                })
                lines.push('')
            }

            lines.push('--- TABLESCAPE ---')
            lines.push(board.tablescape)
            lines.push('')

            lines.push('--- LIGHTING ---')
            lines.push(board.lighting)
            lines.push('')
        }

        if (selectedCake) {
            lines.push('--- CAKE ---')
            lines.push(`  ${selectedCake.name} (${selectedCake.style})`)
            lines.push(`  Tiers: ${selectedCake.tiers} | Servings: ${selectedCake.servings}`)
            lines.push(`  Flavors: ${selectedCake.flavors.join(', ')}`)
            lines.push(`  Decoration: ${selectedCake.decorationStyle}`)
            lines.push(`  Estimated: ${selectedCake.estimatedPrice}`)
            if (selectedCake.dietaryNotes) lines.push(`  Dietary: ${selectedCake.dietaryNotes}`)
            lines.push('')
        }

        if (guestDietarySummary && guestDietarySummary !== 'No special requirements tracked') {
            lines.push('--- DIETARY REQUIREMENTS ---')
            lines.push(guestDietarySummary)
            lines.push('')
        }

        lines.push('Generated by PartyPal (partypal.social)')
        return lines.join('\n')
    }

    const copyBrief = () => {
        const text = buildBriefText()
        navigator.clipboard.writeText(text).catch(() => {})
        showToast('Brief copied to clipboard!', 'success')
    }

    return (
        <div className={styles.briefOverlay} onClick={onClose}>
            <div className={styles.briefModal} onClick={e => e.stopPropagation()}>
                <div className={styles.briefTitle}>Vendor Brief</div>
                <div className={styles.briefSub}>Share this summary with vendors when reaching out about decor, cake, or styling.</div>

                {/* Event */}
                <div className={styles.briefSection}>
                    <div className={styles.briefSectionTitle}>Event Details</div>
                    <div className={styles.briefContent}>
                        {planData.eventType} — {planData.date}{'\n'}
                        {planData.guests} guests at {planData.location}{'\n'}
                        Theme: {planData.theme} | Budget: {planData.budget}
                    </div>
                </div>

                {/* Palette */}
                {board && (
                    <div className={styles.briefSection}>
                        <div className={styles.briefSectionTitle}>Color Palette</div>
                        <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '0.5rem' }}>
                            {board.palette.map((c, i) => (
                                <div key={i} style={{ display: 'flex', alignItems: 'center', gap: '0.3rem', background: 'var(--light-bg)', borderRadius: 8, padding: '0.3rem 0.6rem' }}>
                                    <div style={{ width: 16, height: 16, borderRadius: '50%', background: c.hex, border: '1px solid rgba(0,0,0,0.1)' }} />
                                    <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--navy)' }}>{c.name}</span>
                                    <span style={{ fontSize: '0.68rem', color: '#9aabbb' }}>{c.hex}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* Pinned Inspirations */}
                {pinnedTiles.length > 0 && (
                    <div className={styles.briefSection}>
                        <div className={styles.briefSectionTitle}>Selected Inspirations</div>
                        <div className={styles.briefContent}>
                            {pinnedTiles.map((t, i) => t ? `${t.emoji} ${t.title}: ${t.description}` : '').filter(Boolean).join('\n')}
                        </div>
                    </div>
                )}

                {/* Styling */}
                {board && (
                    <div className={styles.briefSection}>
                        <div className={styles.briefSectionTitle}>Styling Details</div>
                        <div className={styles.briefContent}>
                            Tablescape: {board.tablescape}{'\n'}
                            Lighting: {board.lighting}
                        </div>
                    </div>
                )}

                {/* Cake */}
                {selectedCake && (
                    <div className={styles.briefSection}>
                        <div className={styles.briefSectionTitle}>Cake Preference</div>
                        <div className={styles.briefContent}>
                            {selectedCake.emoji} {selectedCake.name} — {selectedCake.style}{'\n'}
                            {selectedCake.tiers} tiers, {selectedCake.servings} servings{'\n'}
                            Flavors: {selectedCake.flavors.join(', ')}{'\n'}
                            Decoration: {selectedCake.decorationStyle}{'\n'}
                            Estimated: {selectedCake.estimatedPrice}
                            {selectedCake.dietaryNotes ? `\nDietary: ${selectedCake.dietaryNotes}` : ''}
                        </div>
                    </div>
                )}

                {/* Dietary */}
                {guestDietarySummary && guestDietarySummary !== 'No special requirements tracked' && (
                    <div className={styles.briefSection}>
                        <div className={styles.briefSectionTitle}>Dietary Requirements</div>
                        <div className={styles.briefContent}>{guestDietarySummary}</div>
                    </div>
                )}

                <div className={styles.briefActions}>
                    <button className={styles.briefCopyBtn} onClick={copyBrief}>
                        📋 Copy to Clipboard
                    </button>
                    <button className={styles.briefCloseBtn} onClick={onClose}>
                        Close
                    </button>
                </div>
            </div>
        </div>
    )
}
