platform :ios, '15.0'

target 'App' do
  use_frameworks!

  # Google Sign-In via Capacitor plugin (no SPM support, needs CocoaPods)
  pod 'SouthdevsCapacitorGoogleAuth', :path => '../../node_modules/@southdevs/capacitor-google-auth'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
